version: "3.2"
services:
  demopado:
    image: prova-pado1
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    links:
      - rabbitmq:rabbitmq
    networks:
      - my_newtwork
  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my_newtwork

networks:
  default:
    external: true
    name: my_newtwork
  my_newtwork:
    driver: bridge